### ISSUE TITLE
Error npm install -g rubberduck-native

### ISSUE THREAD

**Issue by andrekampll** [karigari/rubberduck#48]
Error while installing "Cannot read property 'toString' of null", log below.

Node -v: 10.16.3
Npm -v: 6.9.0
OS: Windows 10

```
C:\Users\andre
λ npm install -g rubberduck-native

> rubberduck-native@0.6.3 postinstall C:\Users\andre\AppData\Roaming\npm\node_modules\rubberduck-native
> npm run register


> rubberduck-native@0.6.3 register C:\Users\andre\AppData\Roaming\npm\node_modules\rubberduck-native
> node register.js

C:\Users\andre\AppData\Roaming\npm\node_modules\rubberduck-native\register.js:19
  const NPM_ROOT = command.stdout.toString().trim();
                                  ^

TypeError: Cannot read property 'toString' of null
    at Object.<anonymous> (C:\Users\andre\AppData\Roaming\npm\node_modules\rubberduck-native\register.js:19:35)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rubberduck-native@0.6.3 register: `node register.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rubberduck-native@0.6.3 register script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andre\AppData\Roaming\npm-cache\_logs\2019-09-29T21_54_46_590Z-debug.log
npm WARN rollback Rolling back resolve@1.12.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\andre\AppData\Roaming\npm\node_modules\rubberduck-native\node_modules'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rubberduck-native@0.6.3 postinstall: `npm run register`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rubberduck-native@0.6.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andre\AppData\Roaming\npm-cache\_logs\2019-09-29T21_54_47_644Z-debug.log
```

**Comment by ridvanaltun** [comment]
Same issue here.

<details>
<summary>Click to see output</summary> 
 
```
$ npm install -g rubberduck-native
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

> rubberduck-native@0.6.3 postinstall C:\Users\ridva\AppData\Roaming\npm\node_modules\rubberduck-native
> npm run register


> rubberduck-native@0.6.3 register C:\Users\ridva\AppData\Roaming\npm\node_modules\rubberduck-native
> node register.js

C:\Users\ridva\AppData\Roaming\npm\node_modules\rubberduck-native\register.js:19
  const NPM_ROOT = command.stdout.toString().trim();
                                  ^

TypeError: Cannot read property 'toString' of null
    at Object.<anonymous> (C:\Users\ridva\AppData\Roaming\npm\node_modules\rubberduck-native\register.js:19:35)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rubberduck-native@0.6.3 register: `node register.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rubberduck-native@0.6.3 register script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ridva\AppData\Roaming\npm-cache\_logs\2020-03-20T20_16_37_166Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rubberduck-native@0.6.3 postinstall: `npm run register`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rubberduck-native@0.6.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ridva\AppData\Roaming\npm-cache\_logs\2020-03-20T20_16_38_516Z-debug.log
```
</details>
